update README: Adding ToC, how to use the notebooks, descriptions.  Little cleanup
getml/getml-demo pull request #18
Opened 2024-02-26 21:54 UTC by Urfoex

epic &4
issue #35

2024-02-28 07:20 UTC, liuzicheng1987 commented
Why are we using podman here? I think Docker is the standard here and using a tool that many people have never heard of will make adoption harder.

2024-02-28 20:55 UTC, Urfoex commented
> Why are we using podman here? I think Docker is the standard here and using a tool that many people have never heard of will make adoption harder.

Podman is a mostly hazel-free drop-in replacement for Docker. Because of its higher security, it is included in Redhat since version RHEL 8:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.0_release_notes/notable_changes_to_containers

https://www.heise.de/news/Red-Hat-Enterprise-Linux-8-freigeben-Mehr-Flexibilitaet-bei-Software-Versionen-4416725.html#nav_container_im__3

Not to mention: companies with more then 250 people and Mac and Windows users probably evaluated alternatives like Podman-Desktop and [Rancher-Desktop](https://rancherdesktop.io/) because of:
"Commercial use of Docker Desktop at a company of more than 250 employees OR more than $10 million in annual revenue requires a paid subscription (Pro, Team, or Business)."  (https://www.docker.com/products/docker-desktop/)

Define "many people". 
https://github.com/containers/podman has 21K Stars. 

While the docker open source part seems to be now moby
https://stackoverflow.com/questions/47793812/where-is-the-docker-source-code-located-github-repo
https://github.com/moby/moby
with 67K stars.

"Docker being the standard" for what?
The container world is much bigger. 
https://en.wikipedia.org/wiki/List_of_cluster_management_software
https://en.wikipedia.org/wiki/OS-level_virtualization

For simple users trying the notebooks it would be nicer to have a full ready image on a registry.
It seems, there is a getml account;
https://hub.docker.com/u/getml
It would be nicer, to have a full image with notebook and engine on their and ready to run, instead of having the user to build it.
Or on another registry, like 

-     quay.io (redhat)
-     gcr.io (google)
-     public.ecr.aws (amazon)
-     ghcr.io (github)
-     ...

Or simply download the notebooks and run them locally inside their Jupyer-Lab.

Not to mention, podman is a drop-in replacement for docker.
In the repository, there is still just Dockerfile and docker-compose.yml. Just making sure, that the software and libraries inside are provided and run-able as user and not as root.
There is no extra adoption needed. Just reaching a wider audience.

2024-02-29 06:43 UTC, srnnkls commented
Thank you @Urfoex. While I agree with everything you said, I would argue many people – in particular in the data science community – are not familiar with the nuances of Linux containerization. As docker is the best known implementation, we should use that throughout the examples. If you like, maybe, you can reference podman in the readme.

2024-02-29 08:16 UTC, Urfoex commented
Oh, in the docker/README.md. Sorry, I missed that part.
Adjusted.

2024-03-04 00:16 UTC, alxn4 requested changes

2024-03-04 00:16 UTC, alxn4 commented on docker/README.md
> +http://localhost:8888/lab?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Please find a better placeholder for `xxxxxx`. Candidate: <randomly_generated_token>

2024-03-04 00:16 UTC, alxn4 commented on docker/README.md
> +http://localhost:1709/#/token/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
same here

2024-03-04 00:16 UTC, alxn4 commented on README.md
> +http://localhost:8888/lab?token=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
Please find a better placeholder for `xxxxxx...`. Candidate: `<randomly_generated_token>`

2024-03-04 07:46 UTC, srnnkls commented on README.md
> +### Using Docker & Podman
I would propose just using a arch agnostic base image, e.g. the official debian-based `python:3.11` image. I don’t see any benefits in using the outdated manylknux2014 image for a user runtime. Also, we need to expose just the 3.11 version, as users typically don‘t need a 3.8 runtime.

2024-03-04 14:56 UTC, Urfoex commented on README.md
> +### Using Docker & Podman
Moved files into root.
Adjusted base image to python:3.11.8

2024-03-04 15:13 UTC, merged